name: restaurant-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - sqlite
  - pip:
      - fastapi
      - fastmcp
      - uvicorn
      - openai
      - requests
      - python-dotenv
      - pandas
      - google-api-python-client
      - google-auth-httplib2
      - google-auth-oauthlib
